name: Sabotta Imagery
favicon: null
layout_spectrum: 0.9349585603922606
typography_spectrum: 0.5971164619550109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1956873764283955
  lightness: 0.8035752398427576
  saturation: 0.7551114545203745
  rhythmicContrast: 0.10121208289638162
purpose: []
