name: Sabotta Imagery
favicon: null
layout_spectrum: 0.78084
typography_spectrum: 0.92945
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0703'
    - '#7e5900'
    - '#d4c0b9'
    - '#dca530'
    - '#fff8e9'
  brandStrength: 0.1956873764283955
  lightness: 0.8035752398427576
  saturation: 0.7551114545203745
  rhythmicContrast: 0.10121208289638162
purpose: []
